name: tests

# CINTENT >> MANUAL TRIGGER
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#   schedule:
#     # Run every Sunday
#     - cron: '0 0 * * 0'
on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # CINTENT >> UNSUPPORTED_OS
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

        # CINTENT >> REMOVE_MATRIX
        # python-version: [3.6, 3.7]
        python-version: [3.7]

    steps:
    # CINTENT >> CHANGE_VERSION
    # - uses: actions/checkout@v2
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} with Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
      with:
        nonblocking: true

    # CINTENT >> REMOVE_CACHE
    # - name: Get pip cache dir
    #   id: pip-cache
    #   shell: bash -l {0}
    #   run: |
    #     echo "::set-output name=dir::$(python -m pip cache dir)"
        
    # CINTENT >> REMOVE_CACHE
    # - name: Load pip cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ steps.pip-cache.outputs.dir }}
    #     key: ${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
    #     restore-keys: |
    #       ${{ matrix.os }}-${{ matrix.python-version }}-pip-

    - name: Install ffmpeg
      shell: bash -l {0}
      run: |
        conda install -y ffmpeg

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install Cython==0.28.1 --install-option="--no-cython-compile"
        make reqs

    - name: Lint Package
      shell: bash -l {0}
      run: |
        make lint

    - name: Test Package
      shell: bash -l {0}
      run: |
        make test

    - name: Test Build Docs
      shell: bash -l {0}
      run: |
        make docs

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}
